# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cd3359e454859181f077bfafafc970f271e2d4b15b04ad7fe76c3c38ad4f03b42a87f7cf5d4e89f50b2f8cae20bb6ad49665224e6326d02762acd653f3b2905

test:
  secret_key_base: 5692fe02abae5e7a6e14eecc92a40b2db5e8e504a07ceed4ad3c3ea42cabf02239aa19b63be4ec013310ed6c10d877ed8dec5182b4f6d55bab1a72d7eed73905

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
